title: Amulya Pathania
description: Manufacturing Engineering Portfolio

remote_theme: jekyll/minima

minima:
  skin: classic
  include_css:
    - assets/css/custom.css

footer_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/amulya-pathania/
    icon: fab fa-linkedin
