title: Amulya Pathania
description: Manufacturing Engineering Portfolio

plugins:
  - jekyll-include-cache

# the remote theme
remote_theme: "mmistakes/minimal-mistakes@4.27.2"

markdown: kramdown
highlighter: rouge

# Minimal Mistakes settings
minimal_mistakes_skin: "night"  # like: air, aqua, contrast, dark, default, dirt, night, plum, white, storm

#header_pages:
#  - about.md
#  - projects.md
#  - resume.md
