title: Amulya Pathania
description: Manufacturing Engineering Portfolio

theme: minima
minima:
  include_css:
    - /assets/css/custom.css

header_pages:
  - about.md
  - projects.md
  - resume.md

footer_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/amulya-pathania/
    icon: fab fa-linkedin
