title: Amulya Pathania
description: Manufacturing Engineering Portfolio

plugins:
  - jekyll-include-cache

# Use the remote theme
remote_theme: "mmistakes/minimal-mistakes@4.27.2"

# Optional but recommended
markdown: kramdown
highlighter: rouge

# Minimal Mistakes settings
minimal_mistakes_skin: "default"  # You can change to "dark", "air", "sunrise", etc.

#header_pages:
#  - about.md
 # - projects.md
#  - resume.md

#footer_links:
#  - title: LinkedIn
#    url: https://www.linkedin.com/in/amulya-pathania/
 #   icon: fab fa-linkedin
