title: Amulya Pathania
description: Manufacturing Engineering Portfolio
url: "https://amulyapath.github.io"

# Use the remote theme
remote_theme: mmistakes/minimal-mistakes

# Optional: Enable plugins
plugins:
  - jekyll-include-cache

header_pages:
  - about.md
  - projects.md
  - resume.md

footer_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/amulya-pathania/
    icon: fab fa-linkedin
