title: Amulya Pathania
description: Manufacturing Engineering Portfolio

plugins:
  - jekyll-include-cache

# the remote theme
remote_theme: "mmistakes/minimal-mistakes@4.27.2"

markdown: kramdown
highlighter: rouge

# Minimal Mistakes settings
minimal_mistakes_skin: "air"  # all: air, aqua, contrast, dark, default, dirt, neon, night, mint, plum, sunrise (don't like), white, storm

header_pages:
  - welcome.md
  - about.md
  - projects.md
  - resume.md
    
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/amulya-pathania/"
