title: Amulya Pathania
description: Manufacturing Engineering Portfolio
theme: minima
footer_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/amulya-pathania/
    icon: fab fa-linkedin
