title: Amulya Pathania
description: Manufacturing Engineering Portfolio

plugins:
  - jekyll-include-cache

# the remote theme
remote_theme: "mmistakes/minimal-mistakes@4.27.2"
minimal_mistakes_skin: "dark"  # like: air, aqua, contrast, dark, default, night, plum, white, storm

# Plugins
plugins:
  - jekyll-include-cache

# Markdown processor
markdown: kramdown
highlighter: rouge

# Include custom CSS
include:
  - assets/css/custom.css
