title: Amulya Pathania
description: Manufacturing Engineering Portfolio

plugins:
  - jekyll-include-cache

# the remote theme
remote_theme: "mmistakes/minimal-mistakes@4.27.2"

markdown: kramdown
highlighter: rouge

# Minimal Mistakes settings
minimal_mistakes_skin: "default"  # You can change to "dark", "air", "sunrise", etc.

header_pages:
  - about.md
  - resume.md
  - projects.md
    
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/amulya-pathania/"
