title: Amulya Pathania
description: Manufacturing Engineering Portfolio

# Plugins
plugins:
  - jekyll-include-cache

# the remote theme
remote_theme: "mmistakes/minimal-mistakes@4.27.2"
minimal_mistakes_skin: "dark"  # like: air, aqua, contrast, dark (fav), default, night, plum, white, storm

# Markdown processor
markdown: kramdown
highlighter: rouge
